---
- hosts: localhost
  connection: local
  tasks:
    - name: Ensure a directory exists
      ansible.builtin.file:
        path: /tmp/my_test_directory
        state: directory
        mode: '0755'
    - name: Create a test file
      ansible.builtin.copy:
        content: "This is a test file created by Ansible on localhost."
        dest: /tmp/my_test_directory/test_file.txt